'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property BDOCR_API_KEY() As String
            Get
                Return CType(Me("BDOCR_API_KEY"),String)
            End Get
            Set
                Me("BDOCR_API_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property BDOCR_SECRET_KEY() As String
            Get
                Return CType(Me("BDOCR_SECRET_KEY"),String)
            End Get
            Set
                Me("BDOCR_SECRET_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property YDTSL_API_KEY() As String
            Get
                Return CType(Me("YDTSL_API_KEY"),String)
            End Get
            Set
                Me("YDTSL_API_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property YDTSL_SECRET_KEY() As String
            Get
                Return CType(Me("YDTSL_SECRET_KEY"),String)
            End Get
            Set
                Me("YDTSL_SECRET_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property FontCOLOR() As Global.System.Drawing.Color
            Get
                Return CType(Me("FontCOLOR"),Global.System.Drawing.Color)
            End Get
            Set
                Me("FontCOLOR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft JhengHei UI, 20.25pt")>  _
        Public Property FontSTYLE() As Global.System.Drawing.Font
            Get
                Return CType(Me("FontSTYLE"),Global.System.Drawing.Font)
            End Get
            Set
                Me("FontSTYLE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("64, 64, 64")>  _
        Public Property BackCOLOR() As Global.System.Drawing.Color
            Get
                Return CType(Me("BackCOLOR"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BackCOLOR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.61")>  _
        Public Property BackOpacity() As Double
            Get
                Return CType(Me("BackOpacity"),Double)
            End Get
            Set
                Me("BackOpacity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property BDTSL_API_ID() As String
            Get
                Return CType(Me("BDTSL_API_ID"),String)
            End Get
            Set
                Me("BDTSL_API_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property BDTSL_API_KEY() As String
            Get
                Return CType(Me("BDTSL_API_KEY"),String)
            End Get
            Set
                Me("BDTSL_API_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Baidu")>  _
        Public Property TSL_API_Choice() As String
            Get
                Return CType(Me("TSL_API_Choice"),String)
            End Get
            Set
                Me("TSL_API_Choice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property TCTSL_API_ID() As String
            Get
                Return CType(Me("TCTSL_API_ID"),String)
            End Get
            Set
                Me("TCTSL_API_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property TCTSL_API_KEY() As String
            Get
                Return CType(Me("TCTSL_API_KEY"),String)
            End Get
            Set
                Me("TCTSL_API_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property OCR_Detect_Left() As Global.System.Drawing.Point
            Get
                Return CType(Me("OCR_Detect_Left"),Global.System.Drawing.Point)
            End Get
            Set
                Me("OCR_Detect_Left") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property OCR_Detect_Down() As Global.System.Drawing.Point
            Get
                Return CType(Me("OCR_Detect_Down"),Global.System.Drawing.Point)
            End Get
            Set
                Me("OCR_Detect_Down") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AUTO")>  _
        Public Property OCR_Scan_Mode() As String
            Get
                Return CType(Me("OCR_Scan_Mode"),String)
            End Get
            Set
                Me("OCR_Scan_Mode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Baidu")>  _
        Public Property OCR_API_Choice() As String
            Get
                Return CType(Me("OCR_API_Choice"),String)
            End Get
            Set
                Me("OCR_API_Choice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AUTO_STOP() As Boolean
            Get
                Return CType(Me("AUTO_STOP"),Boolean)
            End Get
            Set
                Me("AUTO_STOP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property TCOCR_API_ID() As String
            Get
                Return CType(Me("TCOCR_API_ID"),String)
            End Get
            Set
                Me("TCOCR_API_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("233333333333333")>  _
        Public Property TCOCR_API_KEY() As String
            Get
                Return CType(Me("TCOCR_API_KEY"),String)
            End Get
            Set
                Me("TCOCR_API_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LOG_Switch() As Boolean
            Get
                Return CType(Me("LOG_Switch"),Boolean)
            End Get
            Set
                Me("LOG_Switch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TSL_Switch_BD_API() As Boolean
            Get
                Return CType(Me("TSL_Switch_BD_API"),Boolean)
            End Get
            Set
                Me("TSL_Switch_BD_API") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TSL_Switch_BD_WEB() As Boolean
            Get
                Return CType(Me("TSL_Switch_BD_WEB"),Boolean)
            End Get
            Set
                Me("TSL_Switch_BD_WEB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TSL_Switch_YD_API() As Boolean
            Get
                Return CType(Me("TSL_Switch_YD_API"),Boolean)
            End Get
            Set
                Me("TSL_Switch_YD_API") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TSL_Switch_YD_WEB() As Boolean
            Get
                Return CType(Me("TSL_Switch_YD_WEB"),Boolean)
            End Get
            Set
                Me("TSL_Switch_YD_WEB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TSL_Switch_TC_API() As Boolean
            Get
                Return CType(Me("TSL_Switch_TC_API"),Boolean)
            End Get
            Set
                Me("TSL_Switch_TC_API") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OCR_Predeal_Value() As Integer
            Get
                Return CType(Me("OCR_Predeal_Value"),Integer)
            End Get
            Set
                Me("OCR_Predeal_Value") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property OCR_Predeal_Switch() As Boolean
            Get
                Return CType(Me("OCR_Predeal_Switch"),Boolean)
            End Get
            Set
                Me("OCR_Predeal_Switch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jpn")>  _
        Public Property Origin_Language() As String
            Get
                Return CType(Me("Origin_Language"),String)
            End Get
            Set
                Me("Origin_Language") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Translator.My.MySettings
            Get
                Return Global.Translator.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
